### ISSUE TITLE
Switch between literal and regexp interactively

### ISSUE THREAD

**Issue by raxod502** [raxod502/ctrlf#10]
Currently if you want to switch between literal and regexp searches, you have to exit and come back. We could instead simply bind `C-M-s` and `C-M-r` as toggles during a search.

**Comment by AmaiKinono** [comment]
I think the problem when switching between styles is how to transform the user input. It's easy to transform literal user input to regexp, and non-fuzzy ones to fuzzy ones, but impossible to do the opposite. Similar problem will happen after we have the "word" style.

**Comment by raxod502** [comment]
I think the user will understand that if they switch between modes, the meaning of what they've typed may change. There's no need to try making it magical. In fact, I think a key use case will be the user starting a literal search, typing in a regexp, and realizing that they need to be in regexp mode instead.

**Comment by failable** [comment]
Is there a way to set default style of `C-s` without `C-o s`?

**Comment by AmaiKinono** [comment]
You need to modify `ctrlf-mode-bindings`. I gave an example of modifying such an alist [here](https://github.com/raxod502/selectrum/issues/71#issuecomment-618795989).
