### ISSUE TITLE
Search breaks when entering a hideshow's hidden overlay 

### ISSUE THREAD

**Issue by IrrenWirr** [raxod502/ctrlf#100]
Works well until the search enter a hidden zone made by `hs-minor-mode`.
Then Ctrlf throws an error and becomes unresponsive to further action.

Works as expected:
![works-as-intended](https://user-images.githubusercontent.com/85679298/132096758-3938a419-d429-4e50-8607-1576cd628e9e.png)

Breaks:
![error-and-Ctrfl-becomes-unresponsive](https://user-images.githubusercontent.com/85679298/132096772-2a4a6877-cc8e-4203-af49-deeaabe7a705.png)

The error is triggered by the inappropriate funcall of the function stored in the overlay propriety `isearch-open-invisible-temporary`.
This mismanaged function is defined as :
```elisp
(defun hs-isearch-show-temporary (ov hide-p) ...)
```

**Comment by raxod502** [comment]
Thanks for reporting this and contributing the fix!
