### ISSUE TITLE
Unable to disable ctrlf-mode with (ctrlf-local-mode -1)

### ISSUE THREAD

**Issue by chuxubank** [raxod502/ctrlf#103]
With the latest commit b8a7899

https://github.com/raxod502/ctrlf#disabling-ctrlf-locally This method to temp enable i-search is broken.

Any idea?

**Comment by rileyrg** [comment]
Yup, broken in pdf-tools. 

https://github.com/raxod502/ctrlf#disabling-ctrlf-locally

doesn't work : ctrlf search is still enabled, but doesn't work in pdf. Using pdf-occur for now.

**Comment by raxod502** [comment]
Sorry about that, folks! It turns out to be due to a totally unexpected interaction between a few Emacs systems, which I've worked around in the above-linked commit.
