### ISSUE TITLE
"Invalid regexp" messages are not cleaned up correctly

### ISSUE THREAD

**Issue by AmaiKinono** [raxod502/ctrlf#16]
Basically now I can't type any backslash in regexp search. For example:

```
\(aa\).*\(bb\)
```

It will look like this:

![1](https://user-images.githubusercontent.com/28714352/73519902-34568280-443d-11ea-9f25-e916754d346b.png)

But the warning disappears as long as I finish a valid regexp.

**Comment by raxod502** [comment]
Yes, that's a known problem that I forgot to create an issue for. Basically we fail to `delete-overlay` correctly, so they just build up over time.

**Comment by raxod502** [comment]
This should be fixed now; please test.

**Comment by AmaiKinono** [comment]
It is fixed, but there's a little bug:

- Type `symbol` in `*scratch*` buffer.
- Search `\_<symbol\_>`.
- This happens when you stop at `\_<symbol\`:

![image](https://user-images.githubusercontent.com/28714352/77246983-95454e80-6c67-11ea-89fe-f57c415cd593.png)

The cursor goes between the count and the warning message.

**Comment by raxod502** [comment]
Should be fixed with #3, please test again :)

**Comment by AmaiKinono** [comment]
Yes it's fixed! I took a look of the code, that's definitely some serious effort.
