### ISSUE TITLE
CTRLF stuck when searching symbol

### ISSUE THREAD

**Issue by AmaiKinono** [raxod502/ctrlf#17]
When searching for a symbol, we use this regexp:

```
\_<symbol-name\_>
```

This works fine in `isearch-foward-regexp`, but when typing it in CTRLF, Emacs stucks like forever. Typing `C-g` can recover it, but I can't search anything after that in the current CTRLF session.

I can paste it directly and make CTRLF do the search, so this should be a problem when handling user input.

**Comment by raxod502** [comment]
Sounds like that regexp matches the empty string in an interesting way and CTRLF falls into an infinite loop while trying to list the matches, or something like that. Thanks for the report.

**Comment by raxod502** [comment]
Cannot reproduce; this was likely fixed along with #24. Can you test?

**Comment by AmaiKinono** [comment]
Yes it's fixed.
