### ISSUE TITLE
The overlays refresh a little bit later than the window scrolls

### ISSUE THREAD

**Issue by AmaiKinono** [raxod502/ctrlf#18]
When moving to the next/prev match and the window scrolls, you can see the overlays refresh a little bit later. This is obvious when `ctrlf-highlight-current-line` is on, it feels like flicking.

I tried a little bit and found if I comment out [this `(redisplay)` line](https://github.com/raxod502/ctrlf/blob/c53286a8cb4a9f81c2067902493a3f6019763f09/ctrlf.el#L290), the problem is fixed, but seems that's not the right thing to do.

**Comment by raxod502** [comment]
I can confirm that I see this issue sometimes, although not always. You are correct that removing `(redisplay)` is not the right thing to do, and the comment above it explains why.

**Comment by raxod502** [comment]
Should be fixed now. Let me know what you think.

**Comment by AmaiKinono** [comment]
Yes it's fixed from what I've seen.
