### ISSUE TITLE
What is minibuffer-beginning-of-buffer?

### ISSUE THREAD

**Issue by AmaiKinono** [raxod502/ctrlf#20]
CTRLF remaps `minibuffer-beginning-of-buffer` to ctrlf-first-match, but that doesn't work on my setup, and I didn't find such a command. I changed it to `beginning-of-buffer` and it works. Should this be done?

**Comment by raxod502** [comment]
Apparently it was introduced in Emacs 27, and CI missed it because the byte-compiler doesn't interpret `ctrlf-minibuffer-bindings` as containing function names. See https://github.com/raxod502/ctrlf/commit/24829e5c9a7753bf56fcf01654e46fa19ff396c0.

**Comment by AmaiKinono** [comment]
I see. I'll close the issue then.
