### ISSUE TITLE
Don't inherit hl-line face for ctrlf-highlight-line?

### ISSUE THREAD

**Issue by AmaiKinono** [raxod502/ctrlf#34]
I don't have hl-line-mode enabled, so that face doesn't exist for me. But I don't have a good idea about which face to inherit.

**Comment by raxod502** [comment]
There's a simple solution.

**Comment by AmaiKinono** [comment]
Yes but I feel requiring a package for its face is a little bit overdo it. But of course you don't need to make me satisfied ;)

**Comment by raxod502** [comment]
I said simple, not "most correct" :)
Always open to better alternatives.
