### ISSUE TITLE
Scroll position not restored correctly when aborting search

### ISSUE THREAD

**Issue by raxod502** [raxod502/ctrlf#37]
If you perform a search which takes you away from the original position of point, then when you press `C-g` point is restored correctly but the scroll position of the window may be different. This is a bug.

**Comment by tslilc** [comment]
I'd be interested in helping to solve this problem, but to be sure, is this some issue with the way emacs handles `set-window-point`? There's not a whole lot going on in `ctrlf-cancel`, so i imagine this comes from here:
  
    (set-window-point (minibuffer-selected-window) ctrlf--starting-point)

Did you have any details on this bug?

**Comment by raxod502** [comment]
It probably has something to do with redisplay. After a display change, Emacs does not compute visual line numbers, window lines, etc. until a redisplay has happened. See e.g. [code in Selectrum](https://github.com/raxod502/selectrum/blob/aa11b5efc02f8063dbdb35ee73a4be20a1ddce83/selectrum.el#L489-L536) which works around this issue, and you can also see it [right in `ctrlf-cancel`](https://github.com/raxod502/ctrlf/blob/79377a55df2e39ec0559bd6ec9f2567e8978402e/ctrlf.el#L1032-L1033). As well worked around [in `ctrlf-minibuffer-post-command-hook`](https://github.com/raxod502/ctrlf/blob/79377a55df2e39ec0559bd6ec9f2567e8978402e/ctrlf.el#L675-L691). (Sheesh.)

Actually, looking at `ctrlf-cancel`, would moving the redisplay call to before setting the window point work?

**Comment by tslilc** [comment]
Thanks for the response. I hadn't been using CTRLF for a while, and now using Melpa version `ctrlf-20200523.1558` i can't seem to reproduce this any more. 

I can confirm that removing the `(redisplay)` call from `ctrlf-cancel` re-introduces the issue with every search, but even at it's present location (after `set-window-point`) it seems to be prohibiting the issue for me. Perhaps you have some other way of reproducing this, though.

**Comment by raxod502** [comment]
At first glance just now, I cannot reproduce the issue. Closing for now.
