### ISSUE TITLE
ctrlf-mode is not active on startup

### ISSUE THREAD

**Issue by Jawabiscuit** [raxod502/ctrlf#40]
Snippet of my config:

```
(use-package ctrlf
  :straight (ctrlf
             :type git
             :host github
             :repo "raxod502/ctrlf")
  :config (ctrlf-mode +1)
  :bind (:map minibuffer-local-map
              ("C-r" . ctrlf-backward-literal)))
;; Not sure why
(ctrlf-mode +1)
```

Notice I have to activate ctrlf-mode twice to get it to stay active. Also, another issue I had was having to define "C-r" keybind again even though i-search appeared to be overridden by ctrlf, but only to get C-r's to work in the minibuffer.

**Comment by lynlevenick** [comment]
I had to `(require 'map)` before `ctrlf-mode` could complete successfully.

**Comment by raxod502** [comment]
@lynlevenick that is very puzzling given the following line of code

https://github.com/raxod502/ctrlf/blob/814291e8dbb0c31866d95ae72667e10d48057487/ctrlf.el#L37

**Comment by raxod502** [comment]
@Jawabiscuit the following init-file works for me and should be sufficient to enable all features, can you see if there is something else in your configuration interfering?

```elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(use-package ctrlf
  :straight (:host github :repo "raxod502/ctrlf")
  :defer t
  :init

  (ctrlf-mode +1))
```

**Comment by Jawabiscuit** [comment]
@raxod502, thanks, `:defer t` and `:init` seem to do the trick. I'm not an expert at when to use init vs config so I though config should work, however I didn't think about defer.

**Comment by raxod502** [comment]
I recommend setting `use-package-always-defer` unless you have a very strong reason not to. The default behavior is extremely hard to predict and almost always obstructs understanding of the control flow.
