### ISSUE TITLE
False error when searching closing parenthesis

### ISSUE THREAD

**Issue by AmaiKinono** [raxod502/ctrlf#45]
When searching `)`, `]` or `}`, CTRLF says "No matching parenthesis found", but the search actually success, I can call `ctrlf-next/prev-match` to browse the result.

This happens in all search styles.

**Comment by raxod502** [comment]
This does not occur for me. Is there something else in your configuration interfering?

**Comment by AmaiKinono** [comment]
I can reproduce it in `emacs -Q`. I suspect this is another "Emacs 26" problem (I'm on Emacs 26.3, and the latest version of CTRLF).

Here's the snippet:

``` emacs-lisp
(add-to-list 'load-path "/home/kino/.emacs.d/straight/repos/ctrlf/")
(require 'ctrlf)
(ctrlf-mode)
```

`M-x ctrlf-forward-literal`, then type `)`, this happens:

![image](https://user-images.githubusercontent.com/28714352/82227630-a1454800-995a-11ea-8790-55e8bc0b2332.png)

But just wait for a while, the message will disappear, and the first match is highlighted, everything is back to normal.

I think this is because CTRLF calls `re-search-forward` internally, and if you `M-x re-search-forward RET )`, the same message appears.

**Comment by raxod502** [comment]
That message is actually from `blink-paren-mode`. See `blink-matching-open` in `simple.el`. Does it make sense to disable `blink-paren-mode` in the minibuffer automatically?

**Comment by AmaiKinono** [comment]
> Does it make sense to disable `blink-paren-mode` in the minibuffer automatically?

Well, I'd say it depends. I use `show-paren-mode` so I find this useless, but maybe some users need it. It's rare we need to care about matching parenthesis when searching, but sometimes we do. I don't oppose this change, though.

Maybe it's better to highlight the match and at the same time keep the message, but I wonder if it's possible.

Btw, I didn't find `blink-paren-mode` in Emacs 26. It's controlled by a variable `blink-matching-paren`.

**Comment by raxod502** [comment]
> Btw, I didn't find blink-paren-mode in Emacs 26. It's controlled by a variable blink-matching-paren.

You are correct. My mistake.

> Maybe it's better to highlight the match and at the same time keep the message, but I wonder if it's possible.

In general yes, maybe not with `blink-matching-paren` because I believe it operates by actually moving point and freezing the entire interface. I might be able to hack around it (by making CTRLF run first) but don't want to, so I disabled `blink-matching-paren` in CTRLF.

**Comment by AmaiKinono** [comment]
Thanks!
