### ISSUE TITLE
Use M-s prefix and `search-map` bindings when using ctrlf

### ISSUE THREAD

**Issue by andyleejordan** [raxod502/ctrlf#47]
Hi,

I really want to like this package, especially because of this design principle:

> re-use the flow and keybindings of Isearch

I could never stick with swiper et. al. because, as an _old_ Emacs user, all the semantics of isearch and `search-map` are embedded in my fingers.

The first thing I noticed was that I had a ctrlf search going, and then wanted to pull up my Occur buffer (to go use the handy `occur-edit-mode`). From an ongoing isearch, this is just `M-s o`:

> M-s o runs the command isearch-occur (found in overriding-terminal-local-map)

Which runs occur from isearch. Outside of an isearch, this same binding just runs occur.

A _lot_ of the toggles listed under the core keybindings I think ought to exist under the (overriden) `search-map` bindings, to really uphold the stated design principle. Right now, `M-s` runs the command `next-matching-history-element`, which is completely unexpected as Emacs/isearch user when running a search.

Some others I can think of:

- `M-s o` to switch to occur (as above)
- `M-s r` to toggle regexp/literal (currently on `C-M-s` and `C-M-r`, which are fine to keep too, but also on `C-o s` which isn't Emacsy)
- `M-s .` runs the command `isearch-forward-symbol-at-point` (this works both in and out of an isearch), should run ctrlf with the symbol at point (currently on `M-n`, which also seems fine, but different from isearch)
- `M-s c` toggles case sensitivity (currently on `C-o c` which also isn't Emacsy)
- `M-s e` doesn't need to exist, since it enters isearch edit mode, but ctrlf appears to always be editable

It seems like adding the prefix `C-o` was just a choice made during development, but it's inconsistent with the design principle of re-using the flow and keybindings of isearch. The `search-map` is really handy, and already bound to `M-s`, which a lot of Old Emacs Users already use (and some of us add a lot of other things to the normal `search-map`, like bindings to rgrep and equivalents).

Anyway, ctrlf looks really promising, thanks for the work on it. I just found the lack of `M-s` very jarring as an isearch user.

**Comment by andyleejordan** [comment]
Heh:

> C-w runs the command isearch-yank-word-or-char

Hit this one too. I think it would be ideal if ctrlf were as close as a drop-in upgrade to isearch as possible.

**Comment by raxod502** [comment]
Yep. Great suggestions, thanks.

**Comment by jnboehm** [comment]
I'm also in full support of this, the lack of `C-w` tripped me up.

**Comment by publicimageltd** [comment]
Thanks a lot for a nice package, I like it very much! I just wanted to add 1 for `C-w`, which I use often, too. :-)

**Comment by raxod502** [comment]
Hmmm... actually, not sure I can totally support `C-w` as a top-level binding. Maybe we can put it under `M-s` or something, and we can certainly make the keymap customizable so you could add it yourself, but one of the goals of CTRLF is that the search input behaves normally. So you'd expect `C-w` to kill the region. I suppose I wouldn't be opposed to installing by default a special command that will delegate to `isearch-yank-word-or-char` behavior if and only if there is no active region.

**Comment by publicimageltd** [comment]
Good idea, making it depend on the active region. I tried a simple conditional which checks for active mark, but simply calling `isearch-yank-word-or-char` caused an error. I couldn't find out what caused it. There's some implicit dependence in the code I couldn't figure out. I also tried to explicitly set the text buffer current before calling `isearch....`, no luck. So I came up with this solution, which is at least a first workaround:

```emacs-lisp
  (defun ctrlf-c-w (begin end)
    "Kill region if active, else yank symbol at point."
    (interactive "r")
    (if mark-active
	(kill-region begin end)
      (ctrlf-forward-symbol-at-point)))
```

This works. If you have any ideas how to delegate it to isearch, I'd add this. But as I said, simply calling `isearch-yank-word-or-char`, either with the text buffer explicitly set as current buffer or not, does not work.

**Comment by raxod502** [comment]
Well, looking at the source for `isearch-yank-internal`, I'd say the problem is Isearch keeps point in the actual buffer being searched, while CTRLF keeps it in the minibuffer. Thus `buffer-substring-no-properties` has entirely the wrong effect. Furthermore, `isearch-yank-word-or-char` operates by setting a bunch of Isearch variables and calling some Isearch functions, not by just inserting text into the minibuffer. The whole thing would need to be redone for CTRLF.

Protip: there is a function `use-region-p` you can use instead of checking the `mark-active` variable.
