### ISSUE TITLE
The autoload of CTRLF breaks Emacs startup

### ISSUE THREAD

**Issue by AmaiKinono** [raxod502/ctrlf#49]
I updated to the latest version, then I got this when Emacs startup:

```
Symbol's function definition is void: map-apply
```

The weird thing is even I remove the `use-package` code of CTRLF, this still happens. I looked into it and found it may be caused by this in the autoload:

``` emacs-lisp
(define-minor-mode ctrlf-mode "Minor mode to use CTRLF in place of Isearch.
See `ctrlf-mode-bindings' to customize." :global t :keymap ctrlf--keymap (when ctrlf-mode (setcdr ctrlf--keymap nil) (map-apply (lambda (key cmd) (when (stringp key) (setq key (kbd key))) (define-key ctrlf--keymap key cmd)) ctrlf-mode-bindings)) (with-eval-after-load (quote ctrlf) (if ctrlf-mode (advice-add (function minibuffer-message) :around (function ctrlf--minibuffer-message-condense)) (advice-remove (function minibuffer-message) (function ctrlf--minibuffer-message-condense)))))
```

When I delete `straight/build-cache.el`, Emacs could startup correctly, but when I open Emacs again, it fails. Notice that the `use-package` code of CTRLF is already removed, but I think straight still builds it since it's in `straight/repos`.

A simple fix is add `;;;###autoload` on `(require 'map)`, but I'm not sure if this is a good fix.

**Comment by raxod502** [comment]
> I think straight still builds it since it's in straight/repos.

It should not. If it does, that is a bug, and a very bad one. It may have to do with the autoloads caching system in `straight.el`. You can check on it by seeing if the behavior depends on the value of `straight-cache-autoloads`. If you find that it does seem to be a bug in `straight.el`, I would suggest opening a bug report on that tracker.

> I'm not sure if this is a good fix.

Better is to `(require 'map)` before the usage of `map-apply`. Let me know if the linked commit fixes the issue for you.

**Comment by raxod502** [comment]
If so I will update the changelog.

**Comment by AmaiKinono** [comment]
> If you find that it does seem to be a bug in straight.el, I would suggest opening a bug report on that tracker.

I will if I could find a reproduce recipe.

> Let me know if the linked commit fixes the issue for you.

It does :D

**Comment by raxod502** [comment]
Thanks.
