### ISSUE TITLE
[BUG] CTRLF does not work in the emacs startup loaded buffer

### ISSUE THREAD

**Issue by david-vicente** [raxod502/ctrlf#55]
Starting with an empty config, and adding the following lines

```Emacs-lisp

(setq initial-buffer-choice "buffer1")
(setq straight-repository-branch "develop")
(defvar bootstrap-version)

(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'ctrlf)
(ctrlf-mode +1)
```

If I start Emacs, write something in the buffer and then and press `C-s` or `C-r` once, I get in the mini buffer

`CTRLF ↑ literal: `

but after I write some text and re-press  `C-s` or `C-r` to search for it, instead of navigating through the occurrences I get a message in the mini-buffer:
`I-search backward: [No previous search string]`

and in the `*Messages*` buffer:
`isearch-edit-string: Command attempted to use minibuffer while in minibuffer`

I then have to cancel the command with `C-g` and if I try to use `CTRLF` again, this time it works in the expected way.

This also happens if the user does not suppress the default splash screen.

**Comment by raxod502** [comment]
This should now be fixed. Thank you for the report.

**Comment by david-vicente** [comment]
Thanks!
