### ISSUE TITLE
Incompatibility with package mini-frame 

### ISSUE THREAD

**Issue by JuanGarcia345** [raxod502/ctrlf#57]
Hi!

Really nice package here, it feels very snappy and is simple to use, thank you for your work!

Unfortunately it seems that it's not really compatible with [mini-frame](https://github.com/muffinmad/emacs-mini-frame). For instance, `C-s`  keeps moving the cursor back to the beginning of the prompt and then input is reversed.

To reproduce, evaluate code below in an `emacs -Q` and try `C-s`
```lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'mini-frame)
(straight-use-package 'ctrlf)

(ctrlf-mode +1)
(mini-frame-mode +1)
```

**Comment by raxod502** [comment]
I can confirm the issue. Thank you for the report.

**Comment by raxod502** [comment]
See also https://github.com/raxod502/selectrum/issues/169#issuecomment-670969044.

**Comment by JuanGarcia345** [comment]
Thank you very much for your answer, on my side I'm still using the  version 26.3 of Emacs

``
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2020-05-17, modified by Debian
``

Could this be a problem on the `mini-frame` side?

**Comment by raxod502** [comment]
Unfortunately, I do not know enough about the package to say. You could consider asking the maintainer; perhaps they will be more knowledgeable. It is certainly too early to say which package is at fault, or if it is an Emacs bug.

**Comment by muffinmad** [comment]
With `mini-frame-mode` enabled `(window-buffer (minibuffer-selected-window))` will return minibuffer buffer instead of last selected buffer. Thus `re-search-forward` is running in the minibuffer that leads to the issue.

**Comment by muffinmad** [comment]
Must be fixed by https://github.com/muffinmad/emacs-mini-frame/commit/41d87d123e6f70ea656867356584a7133c28434c

**Comment by raxod502** [comment]
That's great, thank you very much!
