### ISSUE TITLE
ctrlf-occur error when used before the first use of ctrlf

### ISSUE THREAD

**Issue by hsgrott** [raxod502/ctrlf#58]
Hello,

If ctrlf-occur is called before ctrlf is used for the first time, it will fail with a Lisp error (void-function nil).

Steps to reproduce:

1. Open emacs;
2. Execute ctrlf-occur.

Best regards.

**Comment by raxod502** [comment]
Thanks for the report! This should be fixed with the latest commit.

**Comment by hsgrott** [comment]
Hello,

Seems fixed. Now there's a descriptive error message when no prior search was done.

Thanks for your time and for the really amazing packages (ctrlf and selectrum rocks 😄 ).

**Comment by raxod502** [comment]
Great!
