### ISSUE TITLE
Evil-mode integration

### ISSUE THREAD

**Issue by Alexander-Miller** [raxod502/ctrlf#59]
One thing I am still missing from my recent switch from swiper to ctrlf is the former's support for evil mode's search and navigation features. Specifically continuing the last search with n/N and integration with the C-o/C-i jump list.

Note that if you don't want to add a quasi-dependency to evil like swiper did you can also add evil support via https://github.com/emacs-evil/evil-collection

**Comment by raxod502** [comment]
I have no experience with Evil, but I'll be happy to review a pull request. As long as it doesn't thread Evil through more of CTRLF than necessary, optional integration should be fine.

**Comment by Alexander-Miller** [comment]
Done: https://github.com/raxod502/ctrlf/pull/60
