### ISSUE TITLE
how to highlight search hits

### ISSUE THREAD

**Issue by sjLambda** [raxod502/ctrlf#63]
I want to make the matches show up more prominently, say red, instead of just bold. How do I configure that? 

I see the doc says:

- Face ctrlf-highlight-active is used to highlight the currently selected match.

How is it used?

**Comment by raxod502** [comment]
An easy way if you do not feel comfortable with Lisp customizations is to run `M-x describe-face RET ctrlf-highlight-active RET` and click the `customize this face` button, which will allow you to change individual attributes such as the font and color of the face.

Alternatively, you can use the `set-face-*` family of functions to accomplish this programmatically, without the use of Customize. This would be my approach. E.g.,

```elisp
(set-face-background 'ctrlf-highlight-active "#4c3840")
```

**Comment by sjLambda** [comment]
thanks, both methods work
