### ISSUE TITLE
Go to the end of the search candidate on ctrlf-forward commands

### ISSUE THREAD

**Issue by irigone** [raxod502/ctrlf#66]
I used isearch for moving a lot. In my opinion, it's better to go to the end of the search candidate with ctrlf-forward commands and to the beginning of the search candidate with ctrlf-backward commands. Now I use ctrlf and it behaves just a little differently. It always goes to the beginning of the candidate.
I don't feel like copy&pasting everything here so read this issue please abo-abo/avy#316
Also, with isearch-forward, when you are searching forward, it goes to the end of a candidate, but you can go to the beginning of the candidate if you run isearch-backward. which is very useful for keyboard macros.

**Comment by raxod502** [comment]
Yep, I like the default behavior personally but it should be customizable.

**Comment by irigone** [comment]
I wanna code it but I don't know Lisp good enough (yet), although the code seems pretty simple

**Comment by raxod502** [comment]
In case you (or anyone else) decide to try working on this, I think the relevant place to start might be making this movement of point configurable based on the user option: https://github.com/raxod502/ctrlf/blob/2279f684f8d75a75f6b98ddaa908182f08c0d877/ctrlf.el#L671

**Comment by veronikazaglotova** [comment]
Do I have to make it branchless? Like, without if/else?

**Comment by veronikazaglotova** [comment]
I'm currently implementing it, since you showed me the part of the code to change.
AFAIK, ctrlf is aimed to make isearch people feel at home, so I guess it should be default, but since it's your project and you're happy with it, do I make it the default or not?

**Comment by irigone** [comment]
I DID IT! I CODED THE THING! Now I just need a way to NOT hide the cursor when searching, because

1. isearch shows the cursor
2. the user needs to know if the cursor is on the beginning of the match or at the end of the match, it's crucial if you need to go to the beginning/end of a match.

This shouldn't be the default. It's better in a lot of ways, but old users expect it to behave like it behaves now.

**Comment by irigone** [comment]
I was overthinking this. I just made it always go to the end if the custom variable is on.
