### ISSUE TITLE
Search hangs when switching buffers before exiting

### ISSUE THREAD

**Issue by Ypot** [raxod502/ctrlf#74]
Hi.
Thanks for your package, it is already my default search mode.

If the command is not closed properly, it hangs, being impossible to start a new search or continue the one started.
`C-g` doesn't work to "reset". It is solved pressing `M-x`, so a new search can be done.

To reproduce it:

1. `C-s` string
2. click on a different buffer.
3. try to resume the search or start a new one.

**Comment by raxod502** [comment]
Yes, this is in fact a standard behavior of Emacs which is not specific to CTRLF. You can see the same behavior if you do, for example, `C-x C-f`, and then use `C-x o` (or any other binding that changes the active window) to switch out of the minibuffer. Typing `C-g` prints `Quit` in the minibuffer, but does not actually quit the `find-file` session.

Personally, my Emacs configuration contains [an advice that fixes this problem generally](https://github.com/raxod502/radian/blob/27b65bae66ac637d3d244602101d1fffc5257702/emacs/radian.el#L951-L961). I have translated it to use standard Emacs functions:

```elisp
(require 'delsel)
(require 'subr-x)

(define-advice keyboard-quit
    (:around (keyboard-quit))
  "Cause \\[keyboard-quit] to exit the minibuffer, if it is active.                                                                                                                           
Normally, \\[keyboard-quit] will just act in the current buffer.                                                                                                                              
This advice modifies the behavior so that it will instead exit an                                                                                                                             
active minibuffer, even if the minibuffer is not selected."
  (if-let ((minibuffer (active-minibuffer-window)))
      (with-current-buffer (window-buffer minibuffer)
        (minibuffer-keyboard-quit))
    (funcall keyboard-quit)))
```

If you don't use `delsel` you can replace `minibuffer-keyboard-quit` with `abort-recursive-edit`.
