### ISSUE TITLE
C-s, C-r getting rebound

### ISSUE THREAD

**Issue by indigoviolet** [raxod502/ctrlf#82]
I wanted to use the fuzzy search by default and so I did the following (using the `use-package!` macro from doom emacs):

``` elisp
(use-package! ctrlf
  :config
  (ctrlf-mode +1)
  :bind
  ("C-s" . ctrlf-forward-fuzzy)
  ("C-r" . ctrlf-backward-fuzzy)
  )
```

But I find that only the first use of `C-s` is fuzzy, and after that it gets rebound somehow to the literal search. Why is this? How can I fix it?

**Comment by indigoviolet** [comment]
Answering my own question:

This works.
```elisp
(use-package! ctrlf
  :custom
  (ctrlf-mode-bindings '(
                        ("C-s" . ctrlf-forward-fuzzy)
                        ("C-r" . ctrlf-backward-fuzzy)
                        ("C-M-s" . ctrlf-forward-regexp)
                        ("C-M-r" . ctrlf-backward-regexp)
                        )
                       )
  :config
  (ctrlf-mode +1)
  )
```

**Comment by raxod502** [comment]
This will be made more intuitive by https://github.com/raxod502/ctrlf/pull/64
