### ISSUE TITLE
Ctrl-l / auto-recenter don't survive return

### ISSUE THREAD

**Issue by jdtsmith** [raxod502/ctrlf#90]
When you recenter the buffer, or auto-center the current search match, hitting `Return` to exit the mini-buffer changes the window scroll, making it hard to keep track of where your search match is. 

I see the related variable & comment:

```elisp
(defvar ctrlf--final-window-start nil
  "Original buffer's `window-start' just before exiting minibuffer.
For some reason this gets trashed when exiting the minibuffer, so
we restore it to keep the scroll position consistent.

I have literally no idea why this is needed.")
```

But this variable does not seem to be used. Did you intend to:

```elisp
  (set-window-start (get-buffer-window) ctrlf--final-window-start)
```

or similar in `ctrlf--finalize`?  That fixes it for me.

**Comment by rileyrg** [comment]
Yup - well spotted. Works for me too.

https://github.com/rileyrg/ctrlf/tree/auto-recenter-finalize

**Comment by rileyrg** [comment]
#92

**Comment by hikmet517** [comment]
Is this going to be solved, or should I start to look for alternatives?

**Comment by rileyrg** [comment]
@hikmet517 it really is a pita. 😂

**Comment by raxod502** [comment]
See comments on the linked PR.

**Comment by indigoviolet** [comment]
@raxod502 it looks like that PR is stale - any chance you or @rileyrg want to revive it?

**Comment by raxod502** [comment]
Sure, I'll take a look when I have some time, although new feature development and bugfixes for CTRLF aren't my primary focus just at the moment.

**Comment by raxod502** [comment]
This should be solved with https://github.com/raxod502/ctrlf/pull/113, thanks Nicholas!
