### ISSUE TITLE
pcre2el support?

### ISSUE THREAD

**Issue by NicholasBHubbard** [raxod502/ctrlf#95]
Is is possible to get ctrlf to use [pcre2el](https://github.com/joddie/pcre2el) as its regular expression engine much like how [visual-regexp-steroids](https://github.com/benma/visual-regexp-steroids.el) is able to?

Simply enabling the pcre-mode minor mode does not work, which can be tested by putting "1234" in a file and then trying to use ctrlf-forward-regexp with "\d+".

**Comment by raxod502** [comment]
Sure! You can define your own search style:

```elisp
(with-eval-after-load 'ctrlf
  (setf (alist-get 'pcre ctrlf-style-alist)
        `(:prompt "regexp"
                  :translator pcre-to-elisp
                  :case-fold ctrlf-no-uppercase-regexp-p
                  :fallback (isearch-forward-regexp
                             . isearch-backward-regexp)))
  (setq ctrlf-alternate-search-style 'pcre))
```

Also, you should probably pull the latest commit, which improves the behavior of CTRLF when the translation function returns an error (this may happen with `pcre-to-elisp`).

**Comment by NicholasBHubbard** [comment]
This works thank you. This is a great package by the way.

**Comment by raxod502** [comment]
Awesome, glad you like it! <3
