### ISSUE TITLE
Custom face for in-buffer message

### ISSUE THREAD

**Issue by haji-ali** [raxod502/ctrlf#99]
I noticed that there is no way to change the face (especially the background) of the in-buffer message. Having it the same face as the mini-prompt makes it get lost in my text most of the time (most faces already use mini-prompt colors to highlight keywords).

I tried changing the face in `ctrlf--message` but the background get overridden by `ctrlf-highlight-active` I think. 
Is there an easy way to implement this?

**Comment by raxod502** [comment]
Hmm. By in-buffer message, you mean the match count, shown in blue here?

![image](https://user-images.githubusercontent.com/6559064/137831351-4b65ae01-c068-4085-9175-1e976ee646e5.png)

I see what you mean, it looks like both the display of that text and the display of minibuffer messages are controlled by the `minibuffer-prompt` face. It would make sense to add new faces for this, e.g.

* `ctrlf-message-face` (inherits from `minibuffer-prompt` by default) -- factored out in case we later add other places to display messages than the two we have at present
* `ctrlf-minibuffer-message-face` (inherits from `ctrlf-message-face` by default) -- used by `ctrlf--message` always
* `ctrlf-in-buffer-message-face` (inherits from `ctrlf-message-face` by default) -- used by `ctrlf--message` when `ctrlf--message-in-buffer-p` is non-nil

But regarding your issue with the background specifically, you hypothesized that it was being interfered with by `ctrlf-highlight-active`, but you probably want to be looking at `ctrlf-highlight-line` instead.

**Comment by cburroughs** [comment]
>Hmm. By in-buffer message, you mean the match count, shown in blue here?

I'd specifically like to control the face of the match count (`[10/41]' in the screenshot above).

**Comment by raxod502** [comment]
You can now do this by customizing `ctrlf-in-buffer-message-face`.
